#
# Makefile for the Amlogic NAND drivers.
#

obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= dev/        
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= ntd/
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= phy/


obj-$(CONFIG_AML_NFTL_NEW)	+=   aml_nftl_dev.o 
aml_nftl_dev-objs =
aml_nftl_dev-objs += block/aml_nftl_block.o
aml_nftl_dev-objs += block/aml_nftl_init.o
aml_nftl_dev-objs += block/aml_nftl_hw_interface.o
aml_nftl_dev-objs += nftl/aml_nftl_core_20140429.z



